export const CALENDAR_LIST_BASE_ROWS = 5;
export const CALENDAR_LIST_BASE_COLS = 7;
export const CALENDAR_LIST_SECONDARY_ROWS = 4;
export const CALENDAR_LIST_SECONDARY_COLS = 3;
export const CALENDAR_LIST_SECONDARY_LENGTH =
  CALENDAR_LIST_SECONDARY_ROWS * CALENDAR_LIST_SECONDARY_COLS;
